project:
  type: website

website:
  title: "GISProject"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - href: methodology.qmd
        text: Methodology

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

