project:
  type: website

website:
  title: "GISProject"
  navbar:
    left:
      - href: index.html
        text: Home
      - about.qmd
      - href: intro.html
        text: Introduction

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

